### ISSUE TITLE
Some Faces Servlet URL patterns cause resources not to be found

### ISSUE THREAD

**Issue by jlsheehan** [TheCoder4eu/BootsFaces#13]
Superb project, I would like to help if you ever want to provide the source code.

In my web.xml file if I put the faces servlet URL mapping like this:

```
<servlet-mapping>
  <servlet-name>Faces Servlet</servlet-name>
  <url-pattern>*.jsf</url-pattern>
</servlet-mapping>
```

the ".jsf" gets appended to resource requests and glyphicons cannot be found.

If I copy what you have done on your site then I do this:

```
<servlet-mapping>
  <servlet-name>Faces Servlet</servlet-name>
  <url-pattern>/faces/*</url-pattern>
</servlet-mapping>
```

and it all works because the resource suffix is not changed.

Its not a deal breaker I mainly made the issue in case other people are having problems like I was.

One possible solution is here: http://stackoverflow.com/questions/14963756/prevent-suffix-from-being-added-to-resources-when-page-loads

Jeff

**Comment by TheCoder4eu** [comment]
Hi Jeff,
it's nice to hear that you like BootsFaces!
I appreciate very much your interest in contributing to the project, the the codebase is under revision by now, but I'll release it once it is more stable.
Meanwhile any feedback and contribution like yours is very helpul: I was aware of this issue and I was looking for the best solution.
However I didn't stumble on the StackOverflow page you showed me and I'll have a look if it can help me to solve this problem.
Thank you, I'll keep you posted!

**Comment by TheCoder4eu** [comment]
Hi Jeff,
after some experiments to check for a simpler solution, I am testing the Stackoverflow hint.
This solution is from BalusC which I know to be a very reliable source of solutions with regard to JEE/JSF.

I think the best is to leave this kind of config optional, so the developer can activate it if needed.

In practice the need arises if you need to add a suffix to your pages and/or have "_.suffix" in the url-pattern since url-pattern cannot be just "_".

Documentation must be updated to explain how to use this feature.

Regards,
Riccardo

**Comment by TheCoder4eu** [comment]
Thanks, this project is going to be released Opensource in the next few days.

"Superb project, I would like to help if you ever want to provide the source code."

**Comment by TheCoder4eu** [comment]
Testing.

**Comment by jlsheehan** [comment]
K
