### ISSUE TITLE
Source Code in Repo

### ISSUE THREAD

**Issue by mattocchi** [TheCoder4eu/BootsFaces#17]
Hi BootsFaces, is possibile to access your source code, I can't see it on github? I'd like to show it, start using and help you to improve, if I'm able.

**Comment by stephanrauh** [comment]
Hi Mirko,

I'm the author of AngularFaces, not of BootsFaces :). Did Mr. or Mrs. Bootsfaces already answer you? As it happens, I managed to contact them today, so I may be able to forwards your request.

BTW, you'll love AngularFaces, too :).

Best regards,
Stephan

**Comment by TheCoder4eu** [comment]
Hi Mirko,
thank you for your offer to help.
BootsFaces code is still in a stage where there could be heavy refactorings since there are some guideline decisions to take.
For this reason, I will release the code on Github once the codebase will be stable so that everyone can contribute to it without becoming crazy ;-)
However if you wish, I can send/share you a copy of the source code.
Kind Regards,
Riccardo

**Comment by benjmaz** [comment]
Hi Mirko,

I have been checking for bootsfaces source code, however, I don't seem to find it. 

My many intention was to probably extend the functionality by adding accordion and tabs.

Is it possible to share the code so that we can extend the ui components? 

Your response will be appreciated

Regards
Ben

**Comment by TheCoder4eu** [comment]
Hi all and thank you for your interest in Bootsfaces!
When I'll work on the next release I'll take my time and I'll clean out the code and start publishing it on Github.
My hope is that this will let the framework evolve at a quicker pace with the community contribution, as well as leave me more time to spend on another project I am working to.

**Comment by TheCoder4eu** [comment]
## UPDATE

Hi, have a look to my plans to release BootsFaces Source in [Milestone v0.5.0](https://github.com/TheCoder4eu/BootsFaces/milestones/v0.5.0) .

**Comment by lelenoce** [comment]
Hi Riccardo, 
I'm Emanuele, i would like to give a contribute to write some components. 

My contact skype is : emanuele.nocentelli

Best Regards
Emanuele

**Comment by TheCoder4eu** [comment]
Hi, nice that you want to contribute! :-)
I'll keep in touch with you.

**Comment by TheCoder4eu** [comment]
## UPDATE

Hi, have a look to the new repository, where the team has published the source for v0.5.0! :-)

https://github.com/TheCoder4eu/BootsFaces-OSP

**Comment by benjmaz** [comment]
Thanks for the source code. I will check it out and see how I can participate

On Saturday, November 1, 2014 12:40 AM, TheCoder4eu notifications@github.com wrote:

Closed #17.
