### ISSUE TITLE
AddResourcesHandler adds resources in wrong order - BootsFaces 1.2.0

### ISSUE THREAD

**Issue by kvj2020** [TheCoder4eu/BootsFaces#55]
When loading a page with ajax that contains <b:datatable>, the browser console reports the following error: "datatables.min.js:sourcemap:74 Uncaught ReferenceError: jQuery is not defined.". 

This error only occurs when using MyFaces.

**Comment by stephanrauh** [comment]
Fixed by https://github.com/TheCoder4eu/BootsFaces-OSP/commit/887aa0709117c4837ac40ceb8f2aca47f107f52a.

@kvj2020 I'm afraid you've opened the ticket in the wrong repository. Can you open it again at https://github.com/TheCoder4eu/BootsFaces-OSP/issues? Thanks!

@TheCoder4eu Please close this ticket. I don't have the access priviledges to do so. Thanks!
